import Foundation
struct Images {
    static let appcamera = "appcamera"
    static let appphotos = "appphotos"
    static let banker = "banker"
    static let banking = "banking"
    static let bankinggray = "bankinggray"
    static let barmenu = "barmenu"
    static let book = "book"
    static let calendar4 = "calendar4"
    static let checkmark = "checkmark"
    static let gallery = "gallery"
    static let Group14446 = "Group14446"
    static let Home = "Home"
    static let ic_down = "ic_down"
    static let information = "information"
    static let money_bag = "money-bag"
    static let money = "money"
    static let notification = "notification"
    static let phone = "phone"
    static let photo = "photo"
    static let Rectangle6 = "Rectangle6"
    static let Rectangle99 = "Rectangle99"
    static let Rectangle5317 = "Rectangle5317"
    static let Rectangle = "Rectangle"
    static let Rectangleblue = "Rectangleblue"
    static let sort = "sort"
    static let sortinv = "sortinv"
    static let summary = "summary"
    static let Support = "Support"
    static let topnavbarimg = "topnavbarimg"
    static let ic_small_down = "ic_small_down"
    
}
